// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace ApiSoftware.Library35.Parsing
{
	public partial class IfRuleTest
	{
[TestMethod]
[PexGeneratedBy(typeof(IfRuleTest))]
public void ParseTest720()
{
    OutputNode outputNode;
    outputNode = this.ParseTest((string)null);
    Assert.IsNotNull((object)outputNode);
    Assert.AreEqual<string>((string)null, outputNode.Text);
    Assert.IsNotNull(outputNode.Children);
    Assert.AreEqual<int>(0, outputNode.Children.Capacity);
    Assert.AreEqual<int>(0, outputNode.Children.Count);
    Assert.AreEqual<bool>(true, outputNode.IsMatch);
    Assert.AreEqual<int>(0, outputNode.Begin);
    Assert.AreEqual<int>(0, outputNode.End);
    Assert.IsNotNull(outputNode.Rule);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
    Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'", 
                            outputNode.Rule.ErrorTemplate);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
}
[TestMethod]
[PexGeneratedBy(typeof(IfRuleTest))]
public void ParseTest459()
{
    OutputNode outputNode;
    outputNode = this.ParseTest("");
    Assert.IsNotNull((object)outputNode);
    Assert.AreEqual<string>("", outputNode.Text);
    Assert.IsNotNull(outputNode.Children);
    Assert.AreEqual<int>(0, outputNode.Children.Capacity);
    Assert.AreEqual<int>(0, outputNode.Children.Count);
    Assert.AreEqual<bool>(true, outputNode.IsMatch);
    Assert.AreEqual<int>(0, outputNode.Begin);
    Assert.AreEqual<int>(0, outputNode.End);
    Assert.IsNotNull(outputNode.Rule);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
    Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'", 
                            outputNode.Rule.ErrorTemplate);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
}
[TestMethod]
[PexGeneratedBy(typeof(IfRuleTest))]
public void ParseTest341()
{
    OutputNode outputNode;
    outputNode = this.ParseTest("\0");
    Assert.IsNotNull((object)outputNode);
    Assert.AreEqual<string>("\0", outputNode.Text);
    Assert.IsNotNull(outputNode.Children);
    Assert.AreEqual<int>(0, outputNode.Children.Capacity);
    Assert.AreEqual<int>(0, outputNode.Children.Count);
    Assert.AreEqual<bool>(true, outputNode.IsMatch);
    Assert.AreEqual<int>(0, outputNode.Begin);
    Assert.AreEqual<int>(0, outputNode.End);
    Assert.IsNotNull(outputNode.Rule);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
    Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'", 
                            outputNode.Rule.ErrorTemplate);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
}
[TestMethod]
[PexGeneratedBy(typeof(IfRuleTest))]
public void ParseTest667()
{
    OutputNode outputNode;
    outputNode = this.ParseTest("(");
    Assert.IsNotNull((object)outputNode);
    Assert.AreEqual<string>("(", outputNode.Text);
    Assert.IsNotNull(outputNode.Children);
    Assert.AreEqual<int>(4, outputNode.Children.Capacity);
    Assert.AreEqual<int>(2, outputNode.Children.Count);
    Assert.AreEqual<bool>(false, outputNode.IsMatch);
    Assert.AreEqual<int>(0, outputNode.Begin);
    Assert.AreEqual<int>(1, outputNode.End);
    Assert.IsNotNull(outputNode.Rule);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
    Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'", 
                            outputNode.Rule.ErrorTemplate);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
}
[TestMethod]
[PexGeneratedBy(typeof(IfRuleTest))]
public void ParseTest320()
{
    OutputNode outputNode;
    outputNode = this.ParseTest("(\0");
    Assert.IsNotNull((object)outputNode);
    Assert.AreEqual<string>("(\0", outputNode.Text);
    Assert.IsNotNull(outputNode.Children);
    Assert.AreEqual<int>(4, outputNode.Children.Capacity);
    Assert.AreEqual<int>(2, outputNode.Children.Count);
    Assert.AreEqual<bool>(false, outputNode.IsMatch);
    Assert.AreEqual<int>(0, outputNode.Begin);
    Assert.AreEqual<int>(1, outputNode.End);
    Assert.IsNotNull(outputNode.Rule);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
    Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'", 
                            outputNode.Rule.ErrorTemplate);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
}
[TestMethod]
[PexGeneratedBy(typeof(IfRuleTest))]
public void ParseTest995()
{
    OutputNode outputNode;
    outputNode = this.ParseTest("(A)");
    Assert.IsNotNull((object)outputNode);
    Assert.AreEqual<string>("(A)", outputNode.Text);
    Assert.IsNotNull(outputNode.Children);
    Assert.AreEqual<int>(4, outputNode.Children.Capacity);
    Assert.AreEqual<int>(3, outputNode.Children.Count);
    Assert.AreEqual<bool>(true, outputNode.IsMatch);
    Assert.AreEqual<int>(0, outputNode.Begin);
    Assert.AreEqual<int>(3, outputNode.End);
    Assert.IsNotNull(outputNode.Rule);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
    Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'", 
                            outputNode.Rule.ErrorTemplate);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
}
[TestMethod]
[PexGeneratedBy(typeof(IfRuleTest))]
public void ParseTest145()
{
    OutputNode outputNode;
    outputNode = this.ParseTest("(A(");
    Assert.IsNotNull((object)outputNode);
    Assert.AreEqual<string>("(A(", outputNode.Text);
    Assert.IsNotNull(outputNode.Children);
    Assert.AreEqual<int>(4, outputNode.Children.Capacity);
    Assert.AreEqual<int>(3, outputNode.Children.Count);
    Assert.AreEqual<bool>(false, outputNode.IsMatch);
    Assert.AreEqual<int>(0, outputNode.Begin);
    Assert.AreEqual<int>(2, outputNode.End);
    Assert.IsNotNull(outputNode.Rule);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
    Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'", 
                            outputNode.Rule.ErrorTemplate);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
    Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
}
	}
}
