// <copyright file="IfRuleTest.Parse.g.cs">Copyright ©  2013</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;
using Microsoft.Pex.Framework.Moles;
using ApiSoftware.Library35.Parsing.Moles;
using Microsoft.Pex.Framework;
using Microsoft.Moles.Framework;

namespace ApiSoftware.Library35.Parsing
{
	public partial class IfRuleTest
	{
		[TestMethod]
		[PexGeneratedBy(typeof(IfRuleTest))]
		public void Parse877()
		{
			IfRule ifRule;
			OutputNode outputNode;
			ifRule = new IfRule();
			ifRule.Pattern = (string)null;
			ifRule.Rule = (RuleBase)null;
			((RuleBase)ifRule).Name = (string)null;
			((RuleBase)ifRule).Template = (string)null;
			((RuleBase)ifRule).Table = (string)null;
			((RuleBase)ifRule).Column = (string)null;
			outputNode = this.Parse(ifRule, (string)null, 0);
			Assert.IsNotNull((object)outputNode);
			Assert.AreEqual<string>((string)null, outputNode.Text);
			Assert.IsNotNull(outputNode.Children);
			Assert.AreEqual<int>(0, outputNode.Children.Capacity);
			Assert.AreEqual<int>(0, outputNode.Children.Count);
			Assert.AreEqual<bool>(false, outputNode.IsMatch);
			Assert.AreEqual<int>(0, outputNode.Begin);
			Assert.AreEqual<int>(0, outputNode.End);
			Assert.IsNotNull(outputNode.Rule);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
			Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'",
									outputNode.Rule.ErrorTemplate);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
			Assert.IsNotNull((object)ifRule);
			Assert.IsTrue(object.ReferenceEquals((object)ifRule, outputNode.Rule));
		}
		[TestMethod]
		[PexGeneratedBy(typeof(IfRuleTest))]
		[ExpectedException(typeof(ArgumentOutOfRangeException))]
		public void ParseThrowsArgumentOutOfRangeException353()
		{
			IfRule ifRule;
			OutputNode outputNode;
			ifRule = new IfRule();
			ifRule.Pattern = (string)null;
			ifRule.Rule = (RuleBase)null;
			((RuleBase)ifRule).Name = (string)null;
			((RuleBase)ifRule).Template = (string)null;
			((RuleBase)ifRule).Table = (string)null;
			((RuleBase)ifRule).Column = (string)null;
			outputNode = this.Parse(ifRule, (string)null, 1);
		}
		[TestMethod]
		[PexGeneratedBy(typeof(IfRuleTest))]
		[ExpectedException(typeof(ArgumentOutOfRangeException))]
		public void ParseThrowsArgumentOutOfRangeException667()
		{
			IfRule ifRule;
			OutputNode outputNode;
			ifRule = new IfRule();
			ifRule.Pattern = (string)null;
			ifRule.Rule = (RuleBase)null;
			((RuleBase)ifRule).Name = (string)null;
			((RuleBase)ifRule).Template = (string)null;
			((RuleBase)ifRule).Table = (string)null;
			((RuleBase)ifRule).Column = (string)null;
			outputNode = this.Parse(ifRule, (string)null, int.MinValue);
		}
		[TestMethod]
		[PexGeneratedBy(typeof(IfRuleTest))]
		public void Parse718()
		{
			IfRule ifRule;
			OutputNode outputNode;
			ifRule = new IfRule();
			ifRule.Pattern = "";
			ifRule.Rule = (RuleBase)null;
			((RuleBase)ifRule).Name = (string)null;
			((RuleBase)ifRule).Template = (string)null;
			((RuleBase)ifRule).Table = (string)null;
			((RuleBase)ifRule).Column = (string)null;
			outputNode = this.Parse(ifRule, (string)null, 0);
			Assert.IsNotNull((object)outputNode);
			Assert.AreEqual<string>((string)null, outputNode.Text);
			Assert.IsNotNull(outputNode.Children);
			Assert.AreEqual<int>(0, outputNode.Children.Capacity);
			Assert.AreEqual<int>(0, outputNode.Children.Count);
			Assert.AreEqual<bool>(false, outputNode.IsMatch);
			Assert.AreEqual<int>(0, outputNode.Begin);
			Assert.AreEqual<int>(0, outputNode.End);
			Assert.IsNotNull(outputNode.Rule);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
			Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'",
									outputNode.Rule.ErrorTemplate);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
			Assert.IsNotNull((object)ifRule);
			Assert.IsTrue(object.ReferenceEquals((object)ifRule, outputNode.Rule));
		}
		[TestMethod]
		[PexGeneratedBy(typeof(IfRuleTest))]
		public void Parse245()
		{
			IfRule ifRule;
			OutputNode outputNode;
			ifRule = new IfRule();
			ifRule.Pattern = (string)null;
			ifRule.Rule = (RuleBase)null;
			((RuleBase)ifRule).Name = (string)null;
			((RuleBase)ifRule).Template = (string)null;
			((RuleBase)ifRule).Table = (string)null;
			((RuleBase)ifRule).Column = (string)null;
			outputNode = this.Parse(ifRule, "", 0);
			Assert.IsNotNull((object)outputNode);
			Assert.AreEqual<string>("", outputNode.Text);
			Assert.IsNotNull(outputNode.Children);
			Assert.AreEqual<int>(0, outputNode.Children.Capacity);
			Assert.AreEqual<int>(0, outputNode.Children.Count);
			Assert.AreEqual<bool>(false, outputNode.IsMatch);
			Assert.AreEqual<int>(0, outputNode.Begin);
			Assert.AreEqual<int>(0, outputNode.End);
			Assert.IsNotNull(outputNode.Rule);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
			Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'",
									outputNode.Rule.ErrorTemplate);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
			Assert.IsNotNull((object)ifRule);
			Assert.IsTrue(object.ReferenceEquals((object)ifRule, outputNode.Rule));
		}
		[TestMethod]
		[PexGeneratedBy(typeof(IfRuleTest))]
		public void Parse38()
		{
			using (PexChooseBehavedBehavior.Setup())
			{
				SRuleBase sRuleBase;
				IfRule ifRule;
				OutputNode outputNode;
				sRuleBase = new SRuleBase();
				ifRule = new IfRule();
				ifRule.Pattern = "";
				ifRule.Rule = (RuleBase)sRuleBase;
				((RuleBase)ifRule).Name = (string)null;
				((RuleBase)ifRule).Template = (string)null;
				((RuleBase)ifRule).Table = (string)null;
				((RuleBase)ifRule).Column = (string)null;
				outputNode = this.Parse(ifRule, (string)null, 0);
				Assert.IsNull((object)outputNode);
				Assert.IsNotNull((object)ifRule);
				Assert.AreEqual<string>("", ifRule.Pattern);
				Assert.IsNotNull(ifRule.Rule);
				Assert.AreEqual<string>((string)null, ifRule.Rule.Name);
				Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'",
										ifRule.Rule.ErrorTemplate);
				Assert.AreEqual<string>((string)null, ifRule.Rule.Template);
				Assert.AreEqual<string>((string)null, ifRule.Rule.Table);
				Assert.AreEqual<string>((string)null, ifRule.Rule.Column);
				Assert.AreEqual<string>((string)null, ((RuleBase)ifRule).Name);
				Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'",
										((RuleBase)ifRule).ErrorTemplate);
				Assert.AreEqual<string>((string)null, ((RuleBase)ifRule).Template);
				Assert.AreEqual<string>((string)null, ((RuleBase)ifRule).Table);
				Assert.AreEqual<string>((string)null, ((RuleBase)ifRule).Column);
			}
		}
		[TestMethod]
		[PexGeneratedBy(typeof(IfRuleTest))]
		public void Parse121()
		{
			IfRule ifRule;
			IfRule ifRule1;
			OutputNode outputNode;
			ifRule = new IfRule();
			ifRule.Pattern = (string)null;
			ifRule.Rule = (RuleBase)null;
			((RuleBase)ifRule).Name = (string)null;
			((RuleBase)ifRule).Template = (string)null;
			((RuleBase)ifRule).Table = (string)null;
			((RuleBase)ifRule).Column = (string)null;
			ifRule1 = new IfRule();
			ifRule1.Pattern = "";
			ifRule1.Rule = (RuleBase)ifRule;
			((RuleBase)ifRule1).Name = (string)null;
			((RuleBase)ifRule1).Template = (string)null;
			((RuleBase)ifRule1).Table = (string)null;
			((RuleBase)ifRule1).Column = (string)null;
			outputNode = this.Parse(ifRule1, (string)null, 0);
			Assert.IsNotNull((object)outputNode);
			Assert.AreEqual<string>((string)null, outputNode.Text);
			Assert.IsNotNull(outputNode.Children);
			Assert.AreEqual<int>(0, outputNode.Children.Capacity);
			Assert.AreEqual<int>(0, outputNode.Children.Count);
			Assert.AreEqual<bool>(false, outputNode.IsMatch);
			Assert.AreEqual<int>(0, outputNode.Begin);
			Assert.AreEqual<int>(0, outputNode.End);
			Assert.IsNotNull(outputNode.Rule);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
			Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'",
									outputNode.Rule.ErrorTemplate);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
			Assert.IsNotNull((object)ifRule1);
			Assert.AreEqual<string>("", ifRule1.Pattern);
			Assert.IsNotNull(ifRule1.Rule);
			Assert.IsTrue(object.ReferenceEquals(ifRule1.Rule, outputNode.Rule));
			Assert.AreEqual<string>((string)null, ((RuleBase)ifRule1).Name);
			Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'",
									((RuleBase)ifRule1).ErrorTemplate);
			Assert.AreEqual<string>((string)null, ((RuleBase)ifRule1).Template);
			Assert.AreEqual<string>((string)null, ((RuleBase)ifRule1).Table);
			Assert.AreEqual<string>((string)null, ((RuleBase)ifRule1).Column);
		}
		[TestMethod]
		[PexGeneratedBy(typeof(IfRuleTest))]
		public void Parse112()
		{
			IfRule ifRule;
			IfRule ifRule1;
			OutputNode outputNode;
			ifRule = new IfRule();
			ifRule.Pattern = (string)null;
			ifRule.Rule = (RuleBase)null;
			((RuleBase)ifRule).Name = (string)null;
			((RuleBase)ifRule).Template = (string)null;
			((RuleBase)ifRule).Table = (string)null;
			((RuleBase)ifRule).Column = (string)null;
			ifRule1 = new IfRule();
			ifRule1.Pattern = new string('\0', 32);
			ifRule1.Rule = (RuleBase)ifRule;
			((RuleBase)ifRule1).Name = (string)null;
			((RuleBase)ifRule1).Template = (string)null;
			((RuleBase)ifRule1).Table = (string)null;
			((RuleBase)ifRule1).Column = (string)null;
			outputNode = this.Parse(ifRule1, new string('\0', 32), 0);
			Assert.IsNotNull((object)outputNode);
			Assert.AreEqual<string>(new string('\0', 32), outputNode.Text);
			Assert.IsNotNull(outputNode.Children);
			Assert.AreEqual<int>(0, outputNode.Children.Capacity);
			Assert.AreEqual<int>(0, outputNode.Children.Count);
			Assert.AreEqual<bool>(false, outputNode.IsMatch);
			Assert.AreEqual<int>(0, outputNode.Begin);
			Assert.AreEqual<int>(0, outputNode.End);
			Assert.IsNotNull(outputNode.Rule);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
			Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'",
									outputNode.Rule.ErrorTemplate);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
			Assert.IsNotNull((object)ifRule1);
			Assert.AreEqual<string>(new string('\0', 32), ifRule1.Pattern);
			Assert.IsNotNull(ifRule1.Rule);
			Assert.IsTrue(object.ReferenceEquals(ifRule1.Rule, outputNode.Rule));
			Assert.AreEqual<string>((string)null, ((RuleBase)ifRule1).Name);
			Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'",
									((RuleBase)ifRule1).ErrorTemplate);
			Assert.AreEqual<string>((string)null, ((RuleBase)ifRule1).Template);
			Assert.AreEqual<string>((string)null, ((RuleBase)ifRule1).Table);
			Assert.AreEqual<string>((string)null, ((RuleBase)ifRule1).Column);
		}
		[TestMethod]
		[PexGeneratedBy(typeof(IfRuleTest))]
		public void Parse370()
		{
			IfRule ifRule;
			IfRule ifRule1;
			OutputNode outputNode;
			ifRule = new IfRule();
			ifRule.Pattern = (string)null;
			ifRule.Rule = (RuleBase)null;
			((RuleBase)ifRule).Name = (string)null;
			((RuleBase)ifRule).Template = new string('\0', 32);
			((RuleBase)ifRule).Table = (string)null;
			((RuleBase)ifRule).Column = new string('\0', 32);
			ifRule1 = new IfRule();
			ifRule1.Pattern = new string('\0', 32);
			ifRule1.Rule = (RuleBase)ifRule;
			((RuleBase)ifRule1).Name = new string('\0', 32);
			((RuleBase)ifRule1).Template = new string('\0', 32);
			((RuleBase)ifRule1).Table = new string('\0', 32);
			((RuleBase)ifRule1).Column = new string('\0', 32);
			outputNode = this.Parse(ifRule1, new string('\0', 32), 32);
			Assert.IsNotNull((object)outputNode);
			Assert.AreEqual<string>(new string('\0', 32), outputNode.Text);
			Assert.IsNotNull(outputNode.Children);
			Assert.AreEqual<int>(0, outputNode.Children.Capacity);
			Assert.AreEqual<int>(0, outputNode.Children.Count);
			Assert.AreEqual<bool>(true, outputNode.IsMatch);
			Assert.AreEqual<int>(32, outputNode.Begin);
			Assert.AreEqual<int>(32, outputNode.End);
			Assert.IsNotNull(outputNode.Rule);
			Assert.AreEqual<string>(new string('\0', 32), outputNode.Rule.Name);
			Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'",
									outputNode.Rule.ErrorTemplate);
			Assert.AreEqual<string>(new string('\0', 32), outputNode.Rule.Template);
			Assert.AreEqual<string>(new string('\0', 32), outputNode.Rule.Table);
			Assert.AreEqual<string>(new string('\0', 32), outputNode.Rule.Column);
			Assert.IsNotNull((object)ifRule1);
			Assert.IsTrue(object.ReferenceEquals((object)ifRule1, outputNode.Rule));
		}
		[TestMethod]
		[PexGeneratedBy(typeof(IfRuleTest))]
		public void Parse782()
		{
			IfRule ifRule;
			IfRule ifRule1;
			OutputNode outputNode;
			ifRule = new IfRule();
			ifRule.Pattern = (string)null;
			ifRule.Rule = (RuleBase)null;
			((RuleBase)ifRule).Name = (string)null;
			((RuleBase)ifRule).Template = (string)null;
			((RuleBase)ifRule).Table = (string)null;
			((RuleBase)ifRule).Column = (string)null;
			ifRule1 = new IfRule();
			ifRule1.Pattern = "";
			ifRule1.Rule = (RuleBase)ifRule;
			((RuleBase)ifRule1).Name = (string)null;
			((RuleBase)ifRule1).Template = (string)null;
			((RuleBase)ifRule1).Table = (string)null;
			((RuleBase)ifRule1).Column = (string)null;
			outputNode = this.Parse(ifRule1, "", 0);
			Assert.IsNotNull((object)outputNode);
			Assert.AreEqual<string>("", outputNode.Text);
			Assert.IsNotNull(outputNode.Children);
			Assert.AreEqual<int>(0, outputNode.Children.Capacity);
			Assert.AreEqual<int>(0, outputNode.Children.Count);
			Assert.AreEqual<bool>(false, outputNode.IsMatch);
			Assert.AreEqual<int>(0, outputNode.Begin);
			Assert.AreEqual<int>(0, outputNode.End);
			Assert.IsNotNull(outputNode.Rule);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
			Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'",
									outputNode.Rule.ErrorTemplate);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
			Assert.IsNotNull((object)ifRule1);
			Assert.AreEqual<string>("", ifRule1.Pattern);
			Assert.IsNotNull(ifRule1.Rule);
			Assert.IsTrue(object.ReferenceEquals(ifRule1.Rule, outputNode.Rule));
			Assert.AreEqual<string>((string)null, ((RuleBase)ifRule1).Name);
			Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'",
									((RuleBase)ifRule1).ErrorTemplate);
			Assert.AreEqual<string>((string)null, ((RuleBase)ifRule1).Template);
			Assert.AreEqual<string>((string)null, ((RuleBase)ifRule1).Table);
			Assert.AreEqual<string>((string)null, ((RuleBase)ifRule1).Column);
		}
	}
}
