// <copyright file="IntegerRuleTest.Parse.g.cs">Copyright ©  2013</copyright>
// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace ApiSoftware.Library35.Parsing
{
	public partial class IntegerRuleTest
	{
		[TestMethod]
		public void Parse655()
		{
			IntegerRule integerRule;
			OutputNode outputNode;
			integerRule = new IntegerRule();
			((RuleBase)integerRule).Name = (string)null;
			((RuleBase)integerRule).Template = (string)null;
			((RuleBase)integerRule).Table = (string)null;
			((RuleBase)integerRule).Column = (string)null;
			outputNode = this.Parse(integerRule, "", 0);
			Assert.IsNotNull((object)outputNode);
			Assert.AreEqual<string>("", outputNode.Text);
			Assert.AreEqual<bool>(false, outputNode.IsMatch);
			Assert.AreEqual<int>(0, outputNode.Begin);
			Assert.AreEqual<int>(0, outputNode.End);
			Assert.IsNotNull(outputNode.Rule);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
			Assert.AreEqual<string>
				("Error at line {0}, position {1}: Expected an integer but found \'{2}\'",
				 outputNode.Rule.ErrorTemplate);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
			Assert.IsNotNull((object)integerRule);
			Assert.IsTrue(object.ReferenceEquals((object)integerRule, outputNode.Rule));
		}

		[TestMethod]
		[PexGeneratedBy(typeof(IntegerRuleTest))]
		[ExpectedException(typeof(ArgumentOutOfRangeException))]
		public void ParseThrowsArgumentOutOfRangeException150()
		{
			IntegerRule integerRule;
			OutputNode outputNode;
			integerRule = new IntegerRule();
			((RuleBase)integerRule).Name = (string)null;
			((RuleBase)integerRule).Template = (string)null;
			((RuleBase)integerRule).Table = (string)null;
			((RuleBase)integerRule).Column = (string)null;
			outputNode = this.Parse(integerRule, (string)null, 1);
		}

		[TestMethod]
		[PexGeneratedBy(typeof(IntegerRuleTest))]
		[ExpectedException(typeof(ArgumentOutOfRangeException))]
		public void ParseThrowsArgumentOutOfRangeException197()
		{
			IntegerRule integerRule;
			OutputNode outputNode;
			integerRule = new IntegerRule();
			((RuleBase)integerRule).Name = (string)null;
			((RuleBase)integerRule).Template = (string)null;
			((RuleBase)integerRule).Table = (string)null;
			((RuleBase)integerRule).Column = (string)null;
			outputNode = this.Parse(integerRule, (string)null, int.MinValue);
		}

		[TestMethod]
		[PexGeneratedBy(typeof(IntegerRuleTest))]
		[ExpectedException(typeof(ArgumentOutOfRangeException))]
		public void ParseThrowsArgumentOutOfRangeException710()
		{
			IntegerRule integerRule;
			OutputNode outputNode;
			integerRule = new IntegerRule();
			((RuleBase)integerRule).Name = (string)null;
			((RuleBase)integerRule).Template = (string)null;
			((RuleBase)integerRule).Table = (string)null;
			((RuleBase)integerRule).Column = (string)null;
			outputNode = this.Parse(integerRule, "", 1);
		}
		[TestMethod]
		[PexGeneratedBy(typeof(IntegerRuleTest))]
		public void Parse20()
		{
			IntegerRule integerRule;
			OutputNode outputNode;
			integerRule = new IntegerRule();
			((RuleBase)integerRule).Name = (string)null;
			((RuleBase)integerRule).Template = (string)null;
			((RuleBase)integerRule).Table = (string)null;
			((RuleBase)integerRule).Column = (string)null;
			outputNode = this.Parse(integerRule, "", 0);
			Assert.IsNotNull((object)outputNode);
			Assert.AreEqual<string>("", outputNode.Text);
			Assert.IsNotNull(outputNode.Children);
			Assert.AreEqual<int>(0, outputNode.Children.Capacity);
			Assert.AreEqual<int>(0, outputNode.Children.Count);
			Assert.AreEqual<bool>(false, outputNode.IsMatch);
			Assert.AreEqual<int>(0, outputNode.Begin);
			Assert.AreEqual<int>(0, outputNode.End);
			Assert.IsNotNull(outputNode.Rule);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
			Assert.AreEqual<string>
				("Error at line {0}, position {1}: Expected an integer but found \'{2}\'",
				 outputNode.Rule.ErrorTemplate);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
			Assert.IsNotNull((object)integerRule);
			Assert.IsTrue(object.ReferenceEquals((object)integerRule, outputNode.Rule));
		}
		[TestMethod]
		[PexGeneratedBy(typeof(IntegerRuleTest))]
		[PexRaisedException(typeof(AssertFailedException))]
		public void ParseThrowsAssertFailedException767()
		{
			IntegerRule integerRule;
			OutputNode outputNode;
			integerRule = new IntegerRule();
			((RuleBase)integerRule).Name = (string)null;
			((RuleBase)integerRule).Template = (string)null;
			((RuleBase)integerRule).Table = (string)null;
			((RuleBase)integerRule).Column = (string)null;
			outputNode = this.Parse(integerRule, "1", 1);
		}
		[TestMethod]
		[PexGeneratedBy(typeof(IntegerRuleTest))]
		public void Parse387()
		{
			IntegerRule integerRule;
			OutputNode outputNode;
			integerRule = new IntegerRule();
			((RuleBase)integerRule).Name = (string)null;
			((RuleBase)integerRule).Template = (string)null;
			((RuleBase)integerRule).Table = (string)null;
			((RuleBase)integerRule).Column = (string)null;
			outputNode = this.Parse(integerRule, "\0", 0);
			Assert.IsNotNull((object)outputNode);
			Assert.AreEqual<string>("\0", outputNode.Text);
			Assert.IsNotNull(outputNode.Children);
			Assert.AreEqual<int>(0, outputNode.Children.Capacity);
			Assert.AreEqual<int>(0, outputNode.Children.Count);
			Assert.AreEqual<bool>(false, outputNode.IsMatch);
			Assert.AreEqual<int>(0, outputNode.Begin);
			Assert.AreEqual<int>(0, outputNode.End);
			Assert.IsNotNull(outputNode.Rule);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
			Assert.AreEqual<string>
				("Error at line {0}, position {1}: Expected an integer but found \'{2}\'",
				 outputNode.Rule.ErrorTemplate);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
			Assert.IsNotNull((object)integerRule);
			Assert.IsTrue(object.ReferenceEquals((object)integerRule, outputNode.Rule));
		}
		[TestMethod]
		[PexGeneratedBy(typeof(IntegerRuleTest))]
		public void Parse945()
		{
			IntegerRule integerRule;
			OutputNode outputNode;
			integerRule = new IntegerRule();
			((RuleBase)integerRule).Name = (string)null;
			((RuleBase)integerRule).Template = (string)null;
			((RuleBase)integerRule).Table = (string)null;
			((RuleBase)integerRule).Column = (string)null;
			outputNode = this.Parse(integerRule, "1", 0);
			Assert.IsNotNull((object)outputNode);
			Assert.AreEqual<string>("1", outputNode.Text);
			Assert.IsNotNull(outputNode.Children);
			Assert.AreEqual<int>(0, outputNode.Children.Capacity);
			Assert.AreEqual<int>(0, outputNode.Children.Count);
			Assert.AreEqual<bool>(true, outputNode.IsMatch);
			Assert.AreEqual<int>(0, outputNode.Begin);
			Assert.AreEqual<int>(1, outputNode.End);
			Assert.IsNotNull(outputNode.Rule);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
			Assert.AreEqual<string>
				("Error at line {0}, position {1}: Expected an integer but found \'{2}\'",
				 outputNode.Rule.ErrorTemplate);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
			Assert.IsNotNull((object)integerRule);
			Assert.IsTrue(object.ReferenceEquals((object)integerRule, outputNode.Rule));
		}
		[TestMethod]
		[PexGeneratedBy(typeof(IntegerRuleTest))]
		public void Parse669()
		{
			IntegerRule integerRule;
			OutputNode outputNode;
			integerRule = new IntegerRule();
			((RuleBase)integerRule).Name = (string)null;
			((RuleBase)integerRule).Template = (string)null;
			((RuleBase)integerRule).Table = (string)null;
			((RuleBase)integerRule).Column = (string)null;
			outputNode = this.Parse(integerRule, "1", 1);
			Assert.IsNotNull((object)outputNode);
			Assert.AreEqual<string>("1", outputNode.Text);
			Assert.IsNotNull(outputNode.Children);
			Assert.AreEqual<int>(0, outputNode.Children.Capacity);
			Assert.AreEqual<int>(0, outputNode.Children.Count);
			Assert.AreEqual<bool>(false, outputNode.IsMatch);
			Assert.AreEqual<int>(1, outputNode.Begin);
			Assert.AreEqual<int>(1, outputNode.End);
			Assert.IsNotNull(outputNode.Rule);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Name);
			Assert.AreEqual<string>
				("Error at line {0}, position {1}: Expected an integer but found \'{2}\'",
				 outputNode.Rule.ErrorTemplate);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Template);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Table);
			Assert.AreEqual<string>((string)null, outputNode.Rule.Column);
			Assert.IsNotNull((object)integerRule);
			Assert.IsTrue(object.ReferenceEquals((object)integerRule, outputNode.Rule));
		}
	}
}
