// <auto-generated>
// This file contains automatically generated unit tests.
// Do NOT modify this file manually.
// 
// When Pex is invoked again,
// it might remove or update any previously generated unit tests.
// 
// If the contents of this file becomes outdated, e.g. if it does not
// compile anymore, you may delete this file and invoke Pex again.
// </auto-generated>
using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Microsoft.Pex.Framework.Generated;

namespace ApiSoftware.Library35.Parsing
{
	public partial class ChoiceTest
	{
[TestMethod]
[PexGeneratedBy(typeof(ChoiceTest))]
public void Parse633()
{
    Choice choice;
    OutputNode outputNode;
    choice = new Choice();
    ((RuleBase)choice).Name = (string)null;
    ((RuleBase)choice).Template = (string)null;
    ((RuleBase)choice).Table = (string)null;
    ((RuleBase)choice).Column = (string)null;
    ((RuleListBase)choice).Initialize((Rules)null);
    outputNode = this.Parse(choice, 0);
    Assert.IsNull((object)outputNode);
    Assert.IsNotNull((object)choice);
    Assert.IsNotNull(((RuleListBase)choice).Rules);
    Assert.AreEqual<int>(0, ((RuleListBase)choice).Rules.Capacity);
    Assert.AreEqual<int>(0, ((RuleListBase)choice).Rules.Count);
    Assert.AreEqual<string>((string)null, ((RuleBase)choice).Name);
    Assert.AreEqual<string>("Syntax error at line {0}, position {1}: \'{2}\'", 
                            ((RuleBase)choice).ErrorTemplate);
    Assert.AreEqual<string>((string)null, ((RuleBase)choice).Template);
    Assert.AreEqual<string>((string)null, ((RuleBase)choice).Table);
    Assert.AreEqual<string>((string)null, ((RuleBase)choice).Column);
    Assert.IsNull(((RuleBase)choice).Grammar);
}
	}
}
